# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # echo "mtools_skip_check=1" >> ~/.mtoolsrc
    - name: Prerequisites
      run: |
        sudo apt-get install gfortran gcc g++ default-jdk go gnat haskell-platform nodejs python3
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> ~/.profile
        eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        brew install gradle kotlin

    - name: Normal Compile
      run: make -j12

    - name: Test
      run: make test
